#include <iostream>
#include <fstream>
#include <string>
#include <thread>
#include <curl/curl.h>
#include <nlohmann/json.hpp>

using json = nlohmann::json;
using namespace std;

// Function to read a file (e.g., your Discord bot token)
// This function reads the content of a specified file and returns it as a string.
std::string read_file(const std::string& path) {
    std::ifstream file(path);
    if (!file.is_open()) {
        cerr << "Could not open the file: " << path << endl;
        return "";
    }
    std::string content((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
    return content;
}

// Function to send a message to a Discord channel using a webhook
// This function uses the Discord API to send a message to a specified channel.
void send_discord_message(const std::string& token, const std::string& channel_id, const std::string& message) {
    CURL* curl;
    CURLcode res;

    curl = curl_easy_init();
    if (curl) {
        // Construct the URL to send a message to a specific Discord channel
        std::string url = "https://discord.com/api/v9/channels/" + channel_id + "/messages";
        std::string data = "{\"content\":\"" + message + "\"}";

        // Set up the headers for authorization and content type
        struct curl_slist* headers = NULL;
        headers = curl_slist_append(headers, ("Authorization: Bot " + token).c_str());
        headers = curl_slist_append(headers, "Content-Type: application/json");

        // Set the URL and POST data
        curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, data.c_str());

        // Perform the HTTP request
        res = curl_easy_perform(curl);
        if (res != CURLE_OK) {
            fprintf(stderr, "curl_easy_perform() failed: %s\n", curl_easy_strerror(res));
        }

        // Clean up
        curl_easy_cleanup(curl);
    }
}

// Function to fetch weather data using a batch file
// This function executes a batch file that fetches weather data and saves it to a text file.
std::string get_weather_data() {
    // Executes the batch file using the system() command
    system("cmd /c C:\\Users\\YOUR-USERNAME-HERE\\Desktop\\getwttr.bat");

    // Read the contents of the weather.txt file generated by the batch script
    std::ifstream file("C:\\Users\\YOUR-USERNAME-HERE\\Desktop\\weather.txt");
    if (!file.is_open()) {
        return "Error: Could not read weather data.";
    }
    std::string weather((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
    return weather;
}

int main() {
    // Load the Discord bot token from a file
    // The token should be stored in a file named "tok.en" on your desktop
    std::string token = read_file("C:\\Users\\YOUR-USERNAME-HERE\\Desktop\\tok.en");
    std::string channel_id = "YOUR-CHANNEL-ID-HERE"; // Replace with your Discord channel ID

    // Check if the bot token was successfully loaded
    if (token.empty()) {
        std::cerr << "Bot token not found." << std::endl;
        return 1;
    }

    // Send a message to the Discord channel indicating that the bot is online
    send_discord_message(token, channel_id, "Discord Bot Online.");

    // Main loop to handle user commands
    while (true) {
        // Simulate checking for the ".weather" command via user input
        std::string input;
        std::cout << "Enter command: ";
        std::getline(std::cin, input);

        // Handle the ".weather" command
        if (input == ".weather") {
            // Fetch weather data from the batch file and send it to Discord
            std::string weather = get_weather_data();
            send_discord_message(token, channel_id, weather);
        } 
        // Handle the ".help" command
        else if (input == ".help") {
            send_discord_message(token, channel_id, "Need help? Try:\n.weather for current conditions near main campus\n");
        }

        // Add a delay to prevent spamming the Discord API
        std::this_thread::sleep_for(std::chrono::seconds(5));
    }

    return 0;
}

/*
LIMITATIONS & EXPLANATIONS:

1. **Discord API Interaction**:
   - This C++ code uses HTTP requests via `libcurl` to interact with the Discord API.
   - Unlike Python's `discord.py`, which is event-driven and handles incoming messages asynchronously, this C++ implementation relies on manual input to simulate user commands.

2. **No Real-Time Event Handling**:
   - This code does not automatically respond to Discord messages or events. 
   - To achieve real-time interaction similar to `discord.py`, you'd need a more sophisticated event-driven approach using a Discord C++ library (e.g., Sleepy Discord or DPP).

3. **Dependencies**:
   - This code requires `libcurl` for making HTTP requests and `nlohmann/json` for handling JSON data.
   - Make sure these libraries are installed on your system before compiling.

4. **Platform Limitations**:
   - The `system("cmd /c <command>")` call is Windows-specific. For Linux or macOS, you'd need to adjust the batch file execution method.

5. **Error Handling**:
   - This code includes basic error handling, but it may need more robust checks, especially for network-related errors when communicating with the Discord API.

6. **Usage**:
   - Compile the code using: `g++ bot.cpp -o bot -lcurl -std=c++17`
   - Run the executable and follow the prompts to issue commands like ".weather" or ".help".
*/
